version: '2'

# Define the services/containers to be run
services:
  myapp: #name of your service
    build: ./ # specify the directory of the Dockerfile
    restart: always
    env_file: .env
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database # link this service to the database service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    networks:
      - nodeapp-network
      

  database: # name of the service
    image: mongo:4.0.4 # specify image to build container from
    ports:
      - "27017:27017"
    volumes:
      - 'data:/data/db'
    networks:
      - nodeapp-network
      
networks:
  nodeapp-network:
    driver: bridge 

volumes:
  data:
      